### PR TITLE
Add support for GCC 4.8 and Xcode 8

### PR DESCRIPTION
**Pull request by reidhoch**
Adding support for GCC 4.8 and Xcode 8

### CODE REVIEW

**Comment by uilianries** [comment]
Hi @reidhoch !

Do you need those old versions?

**Comment by Croydon** [comment]
Specifically XCode 8 looks curious to me. It builds on macOS 10.11 which is end of life. For the same reason we will start to remove XCode 7.3 builds in the not so distant future.

Isn't it possible for you to at least update to XCode 8.3?

**Comment by reidhoch** [comment]
@uilianries / @Croydon, Unfortunately, yes, we build our Linux product with gcc 4.8, and on the mac side have some dependent libraries stuck on 8.0.

**Comment by Croydon** [comment]
Is privately saving the builds for gtest an option? Just because we don't provide binaries it doesn't mean that it isn't supported. As long as upstream gtest supports these compilers it should continue to work with our recipe

**Comment by uilianries** [comment]
I see no problem in including the two older GTest versions. We have a template that avoids old compilers, but as the distribution idea is to help people with prebuilt packages and GTest is a small library, I feel good including this PR.

**Pull request merged**
